version: 2
updates:
  - package-ecosystem: "yarn"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
    allow:
      - dependency-type: "direct"
        update-type: "widen"
